# Generated by Django 5.2.6 on 2025-09-30 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer_sites', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('alert_type', models.CharField(choices=[('high_block_rate', 'High Block Rate'), ('unusual_traffic', 'Unusual Traffic Pattern'), ('new_threat', 'New Threat Detected'), ('performance_degradation', 'Performance Degradation'), ('geographic_anomaly', 'Geographic Anomaly'), ('rule_triggered', 'Rule Triggered')], max_length=30)),
                ('condition', models.TextField(help_text='JSON condition for triggering alert')),
                ('threshold', models.FloatField(help_text='Threshold value for alert')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_rules', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='active', max_length=15)),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='customer_sites.site')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='tenants.tenant')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='analytics.alertrule')),
            ],
            options={
                'ordering': ['-triggered_at'],
            },
        ),
        migrations.CreateModel(
            name='SecurityReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('daily', 'Daily Security Report'), ('weekly', 'Weekly Security Report'), ('monthly', 'Monthly Security Report'), ('incident', 'Security Incident Report'), ('threat_intel', 'Threat Intelligence Report')], max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField()),
                ('details', models.JSONField(blank=True, default=dict)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='security_reports', to='customer_sites.site')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_reports', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalyticsMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_type', models.CharField(choices=[('requests_total', 'Total Requests'), ('requests_blocked', 'Blocked Requests'), ('requests_allowed', 'Allowed Requests'), ('response_time_avg', 'Average Response Time'), ('bandwidth_used', 'Bandwidth Used'), ('unique_visitors', 'Unique Visitors'), ('top_ips', 'Top IP Addresses'), ('top_rules', 'Top Triggered Rules'), ('geographic_data', 'Geographic Data'), ('hourly_stats', 'Hourly Statistics')], max_length=50)),
                ('value', models.FloatField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analytics_metrics', to='customer_sites.site')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_metrics', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['tenant', 'metric_type', 'timestamp'], name='analytics_a_tenant__cab4b3_idx'), models.Index(fields=['site', 'metric_type', 'timestamp'], name='analytics_a_site_id_047e3a_idx')],
            },
        ),
        migrations.CreateModel(
            name='GeographicData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(max_length=2)),
                ('country_name', models.CharField(max_length=100)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('request_count', models.PositiveIntegerField(default=0)),
                ('blocked_count', models.PositiveIntegerField(default=0)),
                ('allowed_count', models.PositiveIntegerField(default=0)),
                ('threat_count', models.PositiveIntegerField(default=0)),
                ('unique_ips', models.PositiveIntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='geographic_data', to='customer_sites.site')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geographic_data', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-request_count'],
                'unique_together': {('tenant', 'site', 'country_code', 'timestamp')},
            },
        ),
        migrations.CreateModel(
            name='PerformanceMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_time_avg', models.FloatField(help_text='Average response time in milliseconds')),
                ('response_time_p95', models.FloatField(help_text='95th percentile response time in milliseconds')),
                ('response_time_p99', models.FloatField(help_text='99th percentile response time in milliseconds')),
                ('requests_per_second', models.FloatField(help_text='Requests per second')),
                ('error_rate', models.FloatField(help_text='Error rate percentage')),
                ('cpu_usage', models.FloatField(help_text='CPU usage percentage')),
                ('memory_usage', models.FloatField(help_text='Memory usage percentage')),
                ('disk_usage', models.FloatField(help_text='Disk usage percentage')),
                ('bandwidth_in', models.BigIntegerField(help_text='Inbound bandwidth in bytes')),
                ('bandwidth_out', models.BigIntegerField(help_text='Outbound bandwidth in bytes')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='performance_metrics', to='customer_sites.site')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_metrics', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['tenant', 'timestamp'], name='analytics_p_tenant__bf2edc_idx'), models.Index(fields=['site', 'timestamp'], name='analytics_p_site_id_d9274f_idx')],
            },
        ),
        migrations.CreateModel(
            name='ThreatIntelligence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threat_type', models.CharField(choices=[('ip_reputation', 'IP Reputation'), ('malware_signature', 'Malware Signature'), ('attack_pattern', 'Attack Pattern'), ('geo_threat', 'Geographic Threat'), ('user_agent_anomaly', 'User Agent Anomaly')], max_length=30)),
                ('indicator', models.CharField(max_length=500)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=10)),
                ('description', models.TextField(blank=True)),
                ('source', models.CharField(default='internal', max_length=100)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threat_intelligence', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-last_seen'],
                'unique_together': {('tenant', 'threat_type', 'indicator')},
            },
        ),
    ]
