# Generated by Django 5.2.6 on 2025-09-30 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer_sites', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('pattern', models.TextField(help_text='Regex pattern or signature to match')),
                ('description', models.TextField(blank=True)),
                ('is_global', models.BooleanField(default=False, help_text='Apply to all sites by default')),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SiteRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('priority', models.PositiveIntegerField(default=100, help_text='Lower numbers = higher priority')),
                ('custom_pattern', models.TextField(blank=True, help_text='Override the default pattern for this site')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rules.rule')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_rules', to='customer_sites.site')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'ordering': ['priority', 'rule__name'],
                'unique_together': {('site', 'rule')},
            },
        ),
    ]
