"""
Django settings for waf_project project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-us=-1*g$x!+6j)6zig&w1u2p3+^b$1u4snaln8&b0ln)9u!wpc'
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    'jazzmin',  # Must be before django.contrib.admin
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'waf_proxy',
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    # 'captcha',
]
SOCIALACCOUNT_LOGIN_ON_GET = True

# لو عايز التسجيل يتم بالإيميل فقط
ACCOUNT_SIGNUP_FIELDS = ["email*", "password1*", "password2*"]
          # لازم الإيميل

# طرق تسجيل الدخول المسموحة (بما إن مفيش username عندك)
ACCOUNT_LOGIN_METHODS = {"email"}
AUTH_USER_MODEL = 'waf_proxy.User'
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'waf_proxy.middleware.WAFMiddleware',
    'waf_proxy.proxy.ProxyForwardingMiddleware',
    'allauth.account.middleware.AccountMiddleware'
]

ROOT_URLCONF = 'urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'waf_proxy' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom User Model
AUTH_USER_MODEL = 'waf_proxy.User'

# Custom Authentication Backend

SITE_ID = 1

AUTHENTICATION_BACKENDS = (
    'waf_proxy.auth_backend.CustomUserBackend',
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
)
SOCIALACCOUNT_PROVIDERS = {
    "google": {
        "APP": {
            "client_id": "YOUR_GOOGLE_CLIENT_ID",
            "secret": "YOUR_GOOGLE_CLIENT_SECRET",
            "key": ""
        }
    }
}

LOGIN_REDIRECT_URL = '/'
ACCOUNT_EMAIL_VERIFICATION = 'optional'
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': ['profile', 'email'],
        'AUTH_PARAMS': {'access_type': 'online'},
    }
}

# Logging Configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
        'waf_detailed': {
            'format': '[WAF] {asctime} {levelname} | {name} | {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'waf_detailed',
        },
        'waf_file': {
            'class': 'logging.FileHandler',
            'filename': 'waf_debug.log',
            'formatter': 'waf_detailed',
        },
        'proxy_file': {
            'class': 'logging.FileHandler',
            'filename': 'waf_proxy.log',
            'formatter': 'waf_detailed',
        },
    },
    'loggers': {
        'waf_proxy.middleware': {
            'handlers': ['console', 'waf_file'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'waf_proxy.proxy': {
            'handlers': ['console', 'proxy_file'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
}

# Email Configuration
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'  # For development
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'  # For production

# SMTP Settings (uncomment for production)
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'ahmed.a.abuseta@gmail.com'
EMAIL_HOST_PASSWORD = 'fxjt qzli ipja oawe'  # App password for Gmail
EMAIL_TIMEOUT = 30  # Add timeout for SMTP connections

DEFAULT_FROM_EMAIL = 'ahmed.a.abuseta@gmail.com'
EMAIL_SUBJECT_PREFIX = '[WAF Security] '

# Email verification settings
EMAIL_VERIFICATION_TOKEN_EXPIRY_HOURS = 24
EMAIL_MAX_RESEND_ATTEMPTS = 3

RECAPTCHA_PUBLIC_KEY='6Lc6OtQrAAAAAEKVRcDh1ZXvYRJUm-oiOZFLnXnp'
RECAPTCHA_PRIVATE_KEY='6Lc6OtQrAAAAAA7qyeEEUd64NxTRdAL5vMg4KVTZ'

# Site URL for email links
SITE_URL = 'http://localhost:8000'

# Static files (CSS, JavaScript, Images, Videos)
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / 'waf_project' / 'static',
]
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files (user uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'  # Change for production

# Jazzmin Configuration - Cloudflare WAF Admin
JAZZMIN_SETTINGS = {
    "site_title": "Cloudflare WAF Admin",
    "site_header": "Cloudflare WAF",
    "site_brand": "Cloudflare WAF",
    "welcome_sign": "Welcome to Cloudflare WAF Administration",
    "copyright": "Cloudflare WAF Team",
    "site_icon": "admin/img/cloudflare-icon.svg",
    "search_model": ["waf_proxy.User", "waf_proxy.Site", "waf_proxy.Rule"],
    
    # Top Menu Links
    "topmenu_links": [
        {"name": "Admin Dashboard", "url": "admin:index"},
        {"name": "Cloudflare WAF", "url": "admin_dashboard"},
    ],
    
    # User Menu Links  
    "usermenu_links": [
        {"name": "Cloudflare WAF", "url": "admin_dashboard", "icon": "fas fa-chart-line"},
        {"name": "System Status", "url": "system_status", "icon": "fas fa-server"},
    ],
    
    # Sidebar Configuration
    "show_sidebar": True,
    "navigation_expanded": True,
    "order_with_respect_to": ["waf_proxy", "auth"],
    
    # Custom Icons
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "waf_proxy.User": "fas fa-user-shield",
        "waf_proxy.Site": "fas fa-globe",
        "waf_proxy.Rule": "fas fa-shield-virus",
        "waf_proxy.SiteRule": "fas fa-link",
        "waf_proxy.RequestLog": "fas fa-file-alt",
        "waf_proxy.RateLimit": "fas fa-tachometer-alt",
    },
    
    # UI Configuration
    "custom_css": "admin/css/admin_analytics.css",
    "use_google_fonts_cdn": True,
    "show_ui_builder": False,
    "changeform_format": "horizontal_tabs",
    "language_chooser": False,
}

# Jazzmin UI Tweaks - Cloudflare Theme
JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "#f38020",  # Cloudflare Orange
    "accent": "#f38020",  # Cloudflare Orange
    "navbar": "navbar-white navbar-light",
    "no_navbar_border": False,
    "navbar_fixed": True,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-primary",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "default",
    "dark_mode_theme": None,
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    },
    "actions_sticky_top": False
}
