# Generated by Django 5.2.6 on 2025-09-30 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer_sites', '0001_initial'),
        ('rules', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=10)),
                ('path', models.TextField()),
                ('query_string', models.TextField(blank=True)),
                ('remote_ip', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('host', models.CharField(max_length=255)),
                ('action', models.CharField(choices=[('allow', 'Allow'), ('block', 'Block'), ('challenge', 'Challenge')], max_length=10)),
                ('status_code', models.PositiveIntegerField()),
                ('response_time_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('bytes_sent', models.PositiveIntegerField(blank=True, null=True)),
                ('country_code', models.CharField(blank=True, max_length=2)),
                ('country_name', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('request_ts', models.DateTimeField(auto_now_add=True)),
                ('matched_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rules.rule')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_logs', to='customer_sites.site')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_logs', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-request_ts'],
                'indexes': [models.Index(fields=['tenant', 'request_ts'], name='logging_app_tenant__6dc1c3_idx'), models.Index(fields=['site', 'request_ts'], name='logging_app_site_id_c47b7a_idx'), models.Index(fields=['action', 'request_ts'], name='logging_app_action_303396_idx'), models.Index(fields=['remote_ip', 'request_ts'], name='logging_app_remote__e3f0f1_idx')],
            },
        ),
    ]
